[package]
name = "moonshine-view"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A solution to separate saved game state from game view for Bevy and Moonshine Save framework."
homepage = "https://github.com/Zeenobit/moonshine_view"
repository = "https://github.com/Zeenobit/moonshine_view"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.*"
bevy_ecs = "0.13.*"
bevy_hierarchy = "0.13.*"
bevy_utils = "0.13.*"
moonshine-kind = { version = "0.1.*", path = "../kind" }
moonshine-save = { version = "0.3.*", path = "../save" }
moonshine-object = { version = "0.1.*", path = "../object" }

[dev-dependencies]
rand = "0.8.*"
bevy = "0.13.*"
bevy_vector_shapes = "0.7.0"
