[package]
name = "moonshine-view"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Generic Model/View framework designed for Bevy"
categories = ["game-development"]
keywords = ["bevy", "save", "view", "mvc"]
readme = "README.md"
homepage = "https://github.com/Zeenobit/moonshine_view"
repository = "https://github.com/Zeenobit/moonshine_view"

[dependencies]
bevy_app = "0.13.*"
bevy_ecs = "0.13.*"
bevy_hierarchy = "0.13.*"
bevy_utils = "0.13.*"
moonshine-kind = { version = "0.1.*", path = "../../core/crates/kind" }
moonshine-save = { version = "0.3.*", path = "../../core/crates/save" }
moonshine-object = { version = "0.1.*", path = "../../core/crates/object" }

[dev-dependencies]
rand = "0.8.*"
bevy = "0.13.*"
bevy_vector_shapes = "0.7.0"
